
================================================================================
                              VULNERABILITY SCAN REPORT
================================================================================

Scan Summary:
  Total Requests:     883918
  Unique URLs Tested: 309867
  Attack Types Used:  11

Status Code Distribution:
  HTTP 0 : 881131 responses (99.7%)
  HTTP 200 (Success): 2787 responses (0.3%)

Attack Type Distribution:
  ssti: 161718 requests (18.3%)
  path: 120759 requests (13.7%)
  xxe: 115779 requests (13.1%)
  nosql: 113293 requests (12.8%)
  csrf: 99815 requests (11.3%)
  command: 80622 requests (9.1%)
  ssrf: 53007 requests (6.0%)
  xss: 39160 requests (4.4%)
  sqli: 36985 requests (4.2%)
  json: 33580 requests (3.8%)
  html: 29200 requests (3.3%)

Potential Vulnerabilities:
  No clear vulnerabilities detected in the scan results.

Errors Encountered:
  HTTPSConnectionPool(host='b2bcontent.vogel.de', port=443): Max retries exceeded with url: /en/whitepaper/?wg-choose-original=%253C%3Fxml%2520version%3D%25221.0%2522%3F%253E (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x794f3dce8b80>: Failed to establish a new connection: [Errno 111] Connection refused'))): 3 occurrences
  HTTPSConnectionPool(host='b2bcontent.vogel.de', port=443): Max retries exceeded with url: /en/?wg-choose-original=%253C%2521DOCTYPE%2520foo%2520%255B (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x794f3dd7f520>: Failed to establish a new connection: [Errno 111] Connection refused'))): 3 occurrences
  HTTPSConnectionPool(host='b2bcontent.vogel.de', port=443): Max retries exceeded with url: /en/?wg-choose-original=%253C%2521DOCTYPE%2520data%2520%255B (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x794f56f1d4e0>: Failed to establish a new connection: [Errno 111] Connection refused'))): 3 occurrences
  HTTPSConnectionPool(host='b2bcontent.vogel.de', port=443): Max retries exceeded with url: /en/?wg-choose-original=%253C%3Fxml%2520version%3D%25221.0%2522%3F%253E (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x794f3d3e7070>: Failed to establish a new connection: [Errno 111] Connection refused'))): 3 occurrences
  HTTPSConnectionPool(host='b2bcontent.vogel.de', port=443): Max retries exceeded with url: /en/?wg-choose-original=%257B%257Bthis.pop%257D%257D (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x794f3d2a2650>: Failed to establish a new connection: [Errno 111] Connection refused'))): 3 occurrences

================================================================================
                         END OF VULNERABILITY SCAN REPORT
================================================================================

